services:
  accounts:
    build:
      context: .
      dockerfile: Dockerfile
    image: varam0504/accounts:latest
    container_name: accounts-ms
    ports:
      - "8080:8080"
    networks:
      - bank-network

  cards:
    build:
      context: ../cards
      dockerfile: Dockerfile
    image: varam0504/cards:latest
    container_name: cards-ms
    ports:
      - "9000:9000"
    networks:
      - bank-network

  loans:
    build:
      context: ../loans
      dockerfile: Dockerfile
    image: varam0504/loans:latest
    container_name: loans-ms
    ports:
      - "8090:8090"
    networks:
      - bank-network

networks:
  bank-network:
    driver: bridge
